[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
    'pallets/primitives',
    'pallets/parachain-staking',
    'pallets/pallet-inflation',
    'pallets/rmrk-core',
    'pallets/rmrk-equip',
    'pallets/rmrk-market',
]
